from sqlalchemy.orm import Session

from models.dashboard import CatalogService, ServerStatus, UserService


def seed_database(db: Session):
    # Seed Server Status if empty
    if not db.query(ServerStatus).first():
        server_status = ServerStatus(
            id=1,
            nodes_healthy=3,
            nodes_total=3,
            api_server_status="Ready",
            cpu_usage_pct=18,
            cpu_cores=12,
            memory_used_gb=4.2,
            memory_max_gb=32.0,
            storage_used_gb=120,
            storage_max_gb=500,
            storage_assigned_gb=250,
        )
        db.add(server_status)

    # Seed User Services if empty
    if not db.query(UserService).first():
        user_services = [
            UserService(
                id="pyrokube-admin",
                name="pyrokube-admin",
                tag="frontend",
                tag_color="text-kube",
                ready_pods=2,
                total_pods=2,
                status="Running",
                restarts=0,
                image="pyrokube/admin:v0.1.0",
                namespace="default",
                endpoint="pyrokube-admin.default.svc:8080",
                cpu_usage="45m / 500m",
                memory_usage="128MB / 512MB",
            ),
            UserService(
                id="postgres-main",
                name="postgres-main",
                tag="database",
                tag_color="text-kube",
                ready_pods=1,
                total_pods=1,
                status="Running",
                restarts=0,
                image="postgres:16.2-alpine",
                namespace="production",
                endpoint="postgres-main.production.svc:5432",
                cpu_usage="110m / 2000m",
                memory_usage="512MB / 2048MB",
            ),
            UserService(
                id="redis-cache",
                name="redis-cache",
                tag="cache",
                tag_color="text-crit",
                ready_pods=1,
                total_pods=1,
                status="Running",
                restarts=1,
                image="redis:7.2-alpine",
                namespace="production",
                endpoint="redis-cache.production.svc:6379",
                cpu_usage="15m / 500m",
                memory_usage="64MB / 512MB",
            ),
            UserService(
                id="zincsearch-logs",
                name="zincsearch-logs",
                tag="logging",
                tag_color="text-ember",
                ready_pods=1,
                total_pods=1,
                status="Running",
                restarts=0,
                image="zincsearch/zincsearch:v0.4.8",
                namespace="monitoring",
                endpoint="zincsearch-logs.monitoring.svc:4080",
                cpu_usage="60m / 1000m",
                memory_usage="256MB / 1024MB",
            ),
        ]
        db.add_all(user_services)

    # Seed Catalog Services if empty
    if not db.query(CatalogService).first():
        catalog_services = [
            CatalogService(
                id="postgres",
                name="PostgreSQL",
                category="database",
                category_label="Database",
                badge="PG",
                badge_color="text-kube",
                description="Relational SQL database engine with ACID compliance, JSONB support, and full-text search capability.",
                port="5432",
                port_label="Default Port",
                version="v16.2",
                status="Active",
                subtitle="Postgres Relational DB",
            ),
            CatalogService(
                id="mongodb",
                name="MongoDB",
                category="database",
                category_label="Database",
                badge="MDB",
                badge_color="text-ok",
                description="High-performance document-oriented NoSQL database for flexible JSON-like records.",
                port="27017",
                port_label="Default Port",
                version="v7.0.5",
                status="InActive",
                subtitle="NoSQL Document Store",
            ),
            CatalogService(
                id="redis",
                name="Redis",
                category="database",
                category_label="Database",
                badge="RDS",
                badge_color="text-crit",
                description="Ultra-fast in-memory key-value data structure store, cache layer, and pub/sub message broker.",
                port="6379",
                port_label="Default Port",
                version="v7.2.4",
                status="Failed",
                subtitle="In-Memory Cache & Key-Value",
            ),
            CatalogService(
                id="rabbitmq",
                name="RabbitMQ",
                category="database",
                category_label="Database",
                badge="RMQ",
                badge_color="text-warn",
                description="Enterprise AMQP message broker for task queues, background jobs, and event-driven architecture.",
                port="5672 / 15672",
                port_label="Default Port",
                version="v3.13.0",
                status="InActive",
                subtitle="AMQP Message Queue Broker",
            ),
            CatalogService(
                id="zincsearch",
                name="ZincSearch",
                category="database",
                category_label="Database",
                badge="ZNC",
                badge_color="text-ember",
                description="Lightweight search engine and log indexer designed as a low-resource Elasticsearch alternative.",
                port="4080",
                port_label="Default Port",
                version="v0.4.8",
                status="Active",
                subtitle="Search Engine & Log Indexer",
            ),
            CatalogService(
                id="garage",
                name="Garage Storage",
                category="uploads",
                category_label="Uploads",
                badge="GRG",
                badge_color="text-ember",
                description="Geo-distributed, S3-compatible object storage designed for media uploads, buckets, and asset storage.",
                port="3900",
                port_label="S3 API Port",
                version="v1.0.0",
                status="Active",
                subtitle="S3 Object Storage",
            ),
            CatalogService(
                id="registry",
                name="Image Registry",
                category="registry",
                category_label="Image Registry",
                badge="REG",
                badge_color="text-kube",
                description="Private OCI-compliant container image registry for storing, pushing, and pulling docker cluster images.",
                port="5000",
                port_label="Registry Port",
                version="OCI v2",
                status="InActive",
                subtitle="OCI Container Registry",
            ),
        ]
        db.add_all(catalog_services)

    db.commit()
